// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKwHfkS1I5MTyXGyvbJrENw6VytmvDMUc',
    appId: '1:417901648230:web:a2e88f68642c33171a90a7',
    messagingSenderId: '417901648230',
    projectId: 'flutter-ecommerce-app-b1ba6',
    authDomain: 'flutter-ecommerce-app-b1ba6.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-b1ba6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCItE71O2sUXw1oZyG1Ftaf432TuyScfY',
    appId: '1:417901648230:android:6131c1034ae97bcc1a90a7',
    messagingSenderId: '417901648230',
    projectId: 'flutter-ecommerce-app-b1ba6',
    storageBucket: 'flutter-ecommerce-app-b1ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4CTjXcK2avsxgpbauex3252NyUge-4TI',
    appId: '1:417901648230:ios:ba92c92217aeb7401a90a7',
    messagingSenderId: '417901648230',
    projectId: 'flutter-ecommerce-app-b1ba6',
    storageBucket: 'flutter-ecommerce-app-b1ba6.appspot.com',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4CTjXcK2avsxgpbauex3252NyUge-4TI',
    appId: '1:417901648230:ios:fbcc2b0502892c6f1a90a7',
    messagingSenderId: '417901648230',
    projectId: 'flutter-ecommerce-app-b1ba6',
    storageBucket: 'flutter-ecommerce-app-b1ba6.appspot.com',
    iosBundleId: 'com.example.ecommerceProject.RunnerTests',
  );
}
